CREATE TABLE HOTEL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL,
  COUNTRY VARCHAR(200) NOT NULL,
  CITY VARCHAR(200) NOT NULL,
  ADDRESS VARCHAR(500) NOT NULL,
  CONTACT_NO VARCHAR(20) NOT NULL,
  CONSTRAINT HOTEL_PK PRIMARY KEY (ID)
  )