CREATE TABLE BOOKING (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   ROOM_ID BIGINT NOT NULL,
   CHECKIN_DATE DATE NOT NULL,
   CHECKOUT_DATE DATE NOT NULL,
   FIRST_NAME VARCHAR(255) NOT NULL,
   LAST_NAME VARCHAR(255) NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   BOOKING_STATUS VARCHAR(50),
   CONSTRAINT BOOKING_PK PRIMARY KEY (ID),
   CONSTRAINT BOOKING_ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID)
);
