CREATE TABLE ROOM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NUMBER INT NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  PRICE VARCHAR(20) NOT NULL,
  CHECKIN_DATE DATE,
  CHECKOUT_DATE DATE,
  HOTEL_ID BIGINT NOT NULL,
  CONSTRAINT ROOM_PK PRIMARY KEY (ID),
  UNIQUE KEY ROOM_UK (HOTEL_ID, NUMBER)
);
